name: Build Qt6 + OpenCV Project

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        cache: true
        
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: '4.0.0'
        cache: true

    # - name: Install OpenCV and dependencies
    #   run: |
    #     winget update -RunAsAdmin
    #     winget install -RunAsAdmin -y \
    #       libopencv-dev \
    #       build-essential \
    #       cmake \
    #       ninja-build \
    #       pkg-config \
    #       libgl1-mesa-dev

    - name: Run Batch File
      working-directory: ./CameraSDK/OptiTrackCameraSDK_confidential_115_release-3.4.0_BUILD110/CameraSDK/samples/CameraViewerApp
      run: |
        git update-index --chmod=+x ./winBuild.bat
        ./winBuild.bat ./CameraSDK/OptiTrackCameraSDK_confidential_115_release-3.4.0_BUILD110/CameraSDK/samples/CameraViewerApp
